[package]
name = "retox"
version = "0.0.5"
authors = ["Brendan C. <bcopp.oss@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
clap = "2.33.0"
log = "0.4.8"
stderrlog = "0.4.1"
